package com.learnde.pipeline.rules;

import com.learnde.pipeline.models.Alert;
import com.learnde.pipeline.models.Transaction;

import java.io.Serializable;
import java.util.Optional;

/**
 * Interface for alerting rules that evaluate transactions for suspicious patterns.
 *
 * <p>Each rule implements a single detection strategy (threshold, velocity, time-based).
 * Rules are evaluated independently — a transaction may trigger multiple rules,
 * generating one alert per matching rule.
 */
public interface AlertingRule extends Serializable {

    /**
     * Get the unique name of this rule (slug format, e.g., "high-value-transaction").
     *
     * @return the rule name
     */
    String getRuleName();

    /**
     * Get the severity level of alerts generated by this rule.
     *
     * @return severity string (low, medium, high, critical)
     */
    String getSeverity();

    /**
     * Check whether this rule is currently enabled.
     *
     * @return true if the rule should evaluate transactions
     */
    boolean isEnabled();

    /**
     * Evaluate a transaction against this rule.
     *
     * @param transaction the transaction to evaluate
     * @return an Optional containing an Alert if the rule triggers, empty otherwise
     */
    Optional<Alert> evaluate(Transaction transaction);
}
